name: "Set Repository Variable"
author: "action-pack"
description: "Action to set a repository variable."

branding:
  icon: "arrow-right"
  color: "gray-dark"

inputs:
  name:
    description: Name
    required: true

  value:
    description: Value
    required: true

  repository:
    description: Repository name
    default: false
    required: false

  owner:
    description: Repository owner
    default: false
    required: false

  org:
    description: Flag for organization
    default: false
    required: false

  token:
    description: Repository access token
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
