name: "Tag exists"
author: "action-pack"
description: "Action to determine if a tag exists."

branding:
  icon: "tag"
  color: "gray-dark"
  
inputs:
  tag:  
    description: 'Tag to search for'
    required: true
    
  repo:  
    description: 'Repo to search for given tag'
    default: ${{ github.repository }}
    
  github_token:
    description: GitHub token
    default: ${{ github.token }}
    
outputs:
  exists: # id of output
    description: 'true or false'

runs:
  using: node20
  main: dist/index.js
