name: Test

on: 
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      -
        name: Test action
        uses: action-pack/tag-exists@v1
        id: checkTag
        with: 
          tag: 'v1.04'

      - run: echo ${{ steps.checkTag.outputs.exists }}
